[env]
_.python.venv = { path = ".venv", create = true }

[tools]
uv = "0.13.0" # Used for deps
python = "3.15.0" # Required for Ansible
packer = "1.16.1" # Builds base image
prek = "0.5.5" # Pre-commit hooks

[tasks]
install = "uv pip install -r requirements.txt"
