---
# tasks file for base-platform
- name: Set timezone
  community.general.timezone:
    name: Europe/Rome
    hwclock: local
  tags:
    - time

- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags:
    - packages

- name: NodeJS
  ansible.builtin.import_tasks: nvm.yml
  tags:
    - packages
    - extra_packages
    - nvm
    - nodejs
  when: "'nvmnodejs' in enabled_langs"

- name: Python
  ansible.builtin.import_tasks: python.yml
  when: "'python' is in enabled_langs"
  tags:
    - packages
    - extra_packages
    - python

- name: TLS
  ansible.builtin.import_tasks: tls.yml
  when: provision_tls | bool
  tags:
    - tls
    - vault_required

- name: Tailscale
  ansible.builtin.import_tasks: tailscale.yml
  tags:
    - tailscale
    - vault_required

- name: Ensure services enabled
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
    daemon_reexec: true
  loop: "{{ required_services }}"
