---
- name: NVM
  block:
    - name: Get install NVM script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh"
        dest: ${HOME}/nvm_install.sh"
        mode: 0777

    - name: Ensure nvm
      ansible.builtin.shell: "${HOME}/nvm_install.sh"
      args:
        creates: "${HOME}/.nvm/nvm.sh"
        executable: /bin/bash
      changed_when: false

- name: Add Node version and NPM packages
  become: false
  when: ansible_architecture != 'armv6l'
  block:
    - name: Ensure NVM LTS
      ansible.builtin.shell: |
        . $HOME/.nvm/nvm.sh
        nvm install --lts {{ node_version | quote }}
      async: 10
      poll: 5
      args:
        executable: /bin/bash
      ## disable creates for now, since we pass lts as an integer, but nvm creates a
      ## dir as a semver. e.g. we pass 6, but nvm makes v6.17.1
      ## We could do a lookup first of the aliases, or a consul  mapping
      # args:
      #  creates:
      changed_when: false

    - name: Get version
      ansible.builtin.shell: |
        . $HOME/.nvm/nvm.sh
        nvm version {{ node_version }}
      args:
        executable: /bin/bash
      register: nvm_semver
      changed_when: false

    - name: Ensure global npm packages are present
      environment:
        PATH: "{{ ansible_env.PATH }}:${HOME}/.nvm/versions/node/{{ nvm_semver.stdout | trim }}/bin"
      community.general.npm:
        name: "{{ npm.packages | flatten }}"
        global: true
        state: present
        executable: "${HOME}/.nvm/versions/node/{{ nvm_semver.stdout | trim }}/bin/npm"
      when: npm.install_packages | bool | default(false)
