---
# Tasks for tailscale
- name: Add Tailscale Repo
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: "{{ tailscale_pkgs_url }}/{{ ansible_facts['distribution'] | lower }}"
    signed_by: "{{ tailscale_pkgs_url }}/{{ ansible_facts['distribution'] | lower }}/{{ ansible_facts.lsb.codename }}.noarmor.gpg"
    components: main
    state: present
    suites: "{{ ansible_lsb.codename }}"
    install_python_debian: true
    enabled: true

- name: Ensure tailscale package
  become: true
  ansible.builtin.package:
    name: tailscale
    state: present
    update_cache: true

- name: Get tailscale keys from vault
  delegate_to: localhost
  run_once: true
  ansible.builtin.set_fact:
    tailscale_keys: "{{ lookup('community.hashi_vault.vault_kv2_get', 'tailscale', engine_mount_point='hashiatho.me-v2') }}" # noqa yaml
    cacheable: false

# Use the vault key lookup to start tailscale with it's auth key
- name: Start tailscale
  ansible.builtin.command:
    cmd: "tailscale up --auth-key {{ tailscale_keys.data.data['tailscale_auth_key'] }}"
  register: tailscale_up
  changed_when: false
